services:
  getmail:
    image: dungdev20/getmail:latest
    container_name: getmail
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped
